[package]
name = "mirseodb"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4"
time = { version = "0.3", features = ["formatting"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
